
x-mysql-common: &mysql-common
  image: mysql:8.0
  command: >
    --default-authentication-plugin=mysql_native_password
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_unicode_ci
    --max_connections=500
    --innodb_buffer_pool_size=256M
  environment:
    MYSQL_ROOT_PASSWORD: password
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
    interval: 15s
    timeout: 5s
    retries: 40
    start_period: 600s
  networks:
    - accounting-network




services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.10
    command: 
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
    networks:
      - accounting-network

  mysql:
    <<: *mysql-common
    container_name: mysql-generator
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: idgen
    ports:
      - "3318:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - accounting-network

  id-service:
    build: .
    depends_on:
      - etcd
      - mysql
    ports:
      - "9090:9090"
    networks:
      - accounting-network

networks:
  accounting-network:
    external: true

volumes:
  etcd-data:
  mysql-data: